### PR TITLE
Update plugin for publishing to pub.dev

### PR DESCRIPTION
**Pull request by radazzouz**
# Details

The PR updates the relevant files to allow us to publish to https://pub.dev/flutter/packages.

## How to Test

- Checkout this branch locally.
- Go to the root directory of the repo.
- Run `flutter pub pub publish --dry-run` and you should get a similar console output to the one below.

<details>
<summary>flutter pub pub publish --dry-run</summary>

```bash
radazzouz@Rads-MacBook-Pro ~/D/P/g/pspdfkit-flutter> 
flutter pub pub publish --dry-run
Publishing pspdfkit_flutter 1.7.1 to https://pub.dartlang.org:
|-- .github
|   |-- ISSUE_TEMPLATE.md
|   '-- PULL_REQUEST_TEMPLATE.md
|-- .gitignore
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- android
|   |-- .gitignore
|   |-- README.md
|   |-- build.gradle
|   |-- config.gradle
|   |-- gradle
|   |   '-- wrapper
|   |       '-- gradle-wrapper.properties
|   |-- gradle.properties
|   |-- settings.gradle
|   '-- src
|       '-- main
|           |-- AndroidManifest.xml
|           '-- java
|               '-- com
|                   '-- pspdfkit
|                       '-- flutter
|                           '-- pspdfkit
|                               |-- ConfigurationAdapter.java
|                               |-- FlutterPdfActivity.java
|                               |-- PspdfkitPlugin.java
|                               '-- util
|                                   '-- Preconditions.java
|-- example
|   |-- .gitignore
|   |-- .metadata
|   |-- PDFs
|   |   |-- Form_example.pdf
|   |   |-- Guide_v4.pdf
|   |   |-- PSPDFKit Image Example.jpg
|   |   '-- protected.pdf
|   |-- README.md
|   |-- android
|   |   |-- .gitignore
|   |   |-- app
|   |   |   |-- build.gradle
|   |   |   '-- src
|   |   |       '-- main
|   |   |           |-- AndroidManifest.xml
|   |   |           |-- java
|   |   |           |   '-- com
|   |   |           |       '-- pspdfkit
|   |   |           |           '-- flutter
|   |   |           |               '-- example
|   |   |           |                   |-- FlutterExampleApplication.java
|   |   |           |                   '-- MainActivity.java
|   |   |           '-- res
|   |   |               |-- drawable
|   |   |               |   |-- launch_background.xml
|   |   |               |   '-- pspdf_list_divider_light.xml
|   |   |               |-- mipmap-hdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-mdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xxhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               |-- mipmap-xxxhdpi
|   |   |               |   '-- ic_launcher.png
|   |   |               '-- values
|   |   |                   |-- colors.xml
|   |   |                   |-- custom_theme.xml
|   |   |                   |-- dark_theme.xml
|   |   |                   |-- dimens.xml
|   |   |                   '-- styles.xml
|   |   |-- build.gradle
|   |   |-- gradle
|   |   |   '-- wrapper
|   |   |       '-- gradle-wrapper.properties
|   |   |-- gradle.properties
|   |   |-- local.properties.sample
|   |   '-- settings.gradle
|   |-- ios
|   |   |-- .gitignore
|   |   |-- Flutter
|   |   |   |-- AppFrameworkInfo.plist
|   |   |   |-- Debug.xcconfig
|   |   |   '-- Release.xcconfig
|   |   |-- Podfile
|   |   |-- Runner
|   |   |   |-- AppDelegate.h
|   |   |   |-- AppDelegate.m
|   |   |   |-- Assets.xcassets
|   |   |   |   |-- AppIcon.appiconset
|   |   |   |   |   |-- Contents.json
|   |   |   |   |   |-- Icon-App-1024x1024@1x.png
|   |   |   |   |   |-- Icon-App-20x20@1x.png
|   |   |   |   |   | (10 more...)
|   |   |   |   |   |-- Icon-App-76x76@1x.png
|   |   |   |   |   |-- Icon-App-76x76@2x.png
|   |   |   |   |   '-- Icon-App-83.5x83.5@2x.png
|   |   |   |   '-- LaunchImage.imageset
|   |   |   |       |-- Contents.json
|   |   |   |       |-- LaunchImage.png
|   |   |   |       |-- LaunchImage@2x.png
|   |   |   |       |-- LaunchImage@3x.png
|   |   |   |       '-- README.md
|   |   |   |-- Base.lproj
|   |   |   |   |-- LaunchScreen.storyboard
|   |   |   |   '-- Main.storyboard
|   |   |   |-- Info.plist
|   |   |   '-- main.m
|   |   |-- Runner.xcodeproj
|   |   |   |-- project.pbxproj
|   |   |   |-- project.xcworkspace
|   |   |   |   |-- contents.xcworkspacedata
|   |   |   |   '-- xcshareddata
|   |   |   |       '-- IDEWorkspaceChecks.plist
|   |   |   '-- xcshareddata
|   |   |       '-- xcschemes
|   |   |           '-- Runner.xcscheme
|   |   '-- Runner.xcworkspace
|   |       |-- contents.xcworkspacedata
|   |       '-- xcshareddata
|   |           |-- IDEWorkspaceChecks.plist
|   |           '-- WorkspaceSettings.xcsettings
|   |-- lib
|   |   '-- main.dart
|   |-- pubspec.yaml
|   '-- test
|       '-- widget_test.dart
|-- gradle
|   '-- wrapper
|       |-- gradle-wrapper.jar
|       '-- gradle-wrapper.properties
|-- gradlew
|-- gradlew.bat
|-- ios
|   |-- .gitignore
|   |-- Assets
|   |   '-- .gitkeep
|   |-- Classes
|   |   |-- PspdfkitPlugin.h
|   |   '-- PspdfkitPlugin.m
|   |-- README.md
|   '-- pspdfkit_flutter.podspec
|-- lib
|   |-- android_permission_status.dart
|   |-- configuration_options.dart
|   '-- pspdfkit.dart
|-- licenses
|   '-- flutter_simple_permissions.txt
|-- pubspec.yaml
'-- screenshots
    |-- flutter-doctor.png
    |-- ios-always-embed-swift-standard-libraries.png
    |-- ios-deployment-target.png
    '-- ios-info-plist-statusbarappearance.png

Package has 0 warnings.
```

</details>

# Acceptance Criteria

- [ ] Before merging retest all the examples to make sure that they work on both Android and iOS.

### CODE REVIEW

**Review by aksh1t — DISMISSED** [review]
LGTM!

**Comment by dominikheeb** [comment]
Any update when PSPDFKit will be on pub.dev?

**Comment by simoarpe** [comment]
Thank you for the ping @dominikheeb, we're currently re-evaluating the state of this PR as some parts of our cross-platform libraries may be restructured. We'll keep you posted on the progress.

**Comment by davidschreiber** [comment]
Thanks, @dominikheeb, for the ping here. Is it possible for you to use our Flutter library inside your projects without it being published to pub.dev, too, or is this a blocker for your current work in any way?

**Comment by davidschreiber** [comment]
@dominikheeb our team is currently discussing the next steps here, and wondered whether you are already using pspdfkit-flutter in one of your projects? We'd like to link you to an existing customer account (if one exists) or know whether you are currently only evaluating the feasibility of our library for your purposes?

**Comment by dominikheeb** [comment]
> Thanks, @dominikheeb, for the ping here. Is it possible for you to use our Flutter library inside your projects without it being published to pub.dev, too, or is this a blocker for your current work in any way?

We are using it in a project with a license and for us it's not blocking the development but the build is not that reliable since often pspdfkit has a change on the repository and then our build breaks due to the cocoapods expecting a different version.

Using pub.dev and releases would allow us have a more reliable build and i think it would make to have a new release when you publish new functionality which then would also be more transparent

**Comment by davidschreiber** [comment]
Thank you very much for your feedback! I really appreciate the input, and agree with you that pub.dev support will improve reliability and make integration and maintenance simpler. While I can't give you a definitive timeframe for the pub.dev migration, I can assure you that this is still on our roadmap, and will happen next year. Thanks for bearing with us!

**Comment by amit-nayar** [comment]
Closing this PR as we are currently working on publishing to pub.dev internally. An update will be posted here when this happens.

**Comment by davidschreiber** [comment]
@dominikheeb we recently published our latest version to pub.dev, and future version will also be always published there as well: https://pub.dev/packages/pspdfkit_flutter

The README in this repo is not yet fully up-to-date. We're working on improved documentation for our Flutter product, which includes a clearer README, which we plan to ship soon.

**Pull request closed without merging**
