### PR TITLE
Standardized the package for pub.dev standards

### PR DESCRIPTION
**Pull request by imdatsolak**
# Details

The usual way of using packages in flutter/dart is to perform an `import 'package:<packagename>/<packagename>.dart`. Unfortunately, PSPDFKit required the import of implementation specifics which makes it unusable.

The changes introduced are mainly to:
- standardize the import 
- fix a clean-code issue in the iOS-Version (please use the actual class of an object, not its superclass)

# Acceptance Criteria

- [x] Before merging retest all the examples to make sure that they work on both Android and iOS.

### CODE REVIEW

**Comment by imdatsolak** [comment]
Added initial support for displaying PDFs with Watermarks when using `global` mode (i.e. `PSPDFKit.present(...)`) with a new call named `PSPDFKit.presentWithWatermark(String documentPath, String watermarkString, [ <...further params ...> ])`.

Also added a few more callbacks for the Activity LifeCycle information, which we also need in the iOS-Version.

Just FYI: Over time, I may add support for Windows and macOS as well as (hopefully) `PspdfkitWidget` for all of them. But for that, I will probably need some support.

**Comment by aksh1t** [comment]
Hi @imdatsolak! Thank you for your contribution. 
Can you please sign the CLA from [the "Contributing" section of the README](https://github.com/PSPDFKit/pspdfkit-flutter#contributing) so we can start reviewing and testing the pull request?
Please note that signing the CLA does not guarantee that we will accept and merge this PR.
If you have any questions or concerns, please reach out to our support portal at https://support.pspdfkit.com/hc/en-us/requests/new - we're happy to provide support there for our commercial SDK.
Once again, thank you very much for your contribution!

**Comment by imdatsolak** [comment]
Hello based on some Ticket-feedback I received (and because adding the Watermark-Feature to this repo was just an honest mistake), I have removed the watermark feature.
I have added the Activity LifeCycle-callbacks though as they are needed anyway.

**Comment by imdatsolak** [comment]
> Hi @imdatsolak! Thank you for your contribution.
> Can you please sign the CLA from [the "Contributing" section of the README](https://github.com/PSPDFKit/pspdfkit-flutter#contributing) so we can start reviewing and testing the pull request?
> Please note that signing the CLA does not guarantee that we will accept and merge this PR.
> If you have any questions or concerns, please reach out to our support portal at https://support.pspdfkit.com/hc/en-us/requests/new - we're happy to provide support there for our commercial SDK.
> Once again, thank you very much for your contribution!

I have signed the CLA.

**Pull request closed without merging**
