### PR TITLE
Expose Configuration action buttons

### PR DESCRIPTION
**Pull request by radazzouz**
Solves #25 

---

- [x] Expose Configuration action buttons on Android.
- [x] Expose Configuration action buttons on iOS.

### CODE REVIEW

**Comment by radazzouz** [comment]
> The code looks okay to me, however I wasn't able to see the back / forward buttons when navigating using the tab bar (after I changed them to true in `main.dart`). Maybe navigation like that does not count as a PDF Action?

The best way to show the action navigation buttons on iOS is to use use link annotations (GoToActions) to another page.

recording

**Comment by aksh1t** [comment]
Sorry for the delay in reviewing and for the noob question. I was able to confirm that it works correctly. Everything looks good.

**Comment by irgendeinich** [comment]
@radazzouz 
On Android we only have a single setting `hideNavigationButtons` and `showNavigationButtons` which is for both forward and backward buttons. If we want to expose forward and backward separately on iOS we should prefix the configuration option with iOS.

In my opinion it would make sense though to just have one unified setting that enables and disables both buttons on both iOS and Android. I'd call it `showNavigationButtons` or `showForwardBackwardButtons`.

WDYT?

**Comment by radazzouz** [comment]
@irgendeinich, I fully agree. I will make the changes on iOS to use a single property.

I'd like to use a very expressive name. How about `showBackForwardActionButtons` or `showActionNavigationButtons`?

Also, I will prefix `showBackForwardActionButtonLabels` with `iOS` since it's only available there. I'll rename it to `iOSShowBackForwardActionButtonLabels`.

**Comment by irgendeinich** [comment]
I'd go with `showActionNavigationButtons`.

**Comment by radazzouz** [comment]
All done! Thank you, @irgendeinich! Feel free to push the Android changes on this branch.

**Pull request merged**
